import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
    en: {
        translation: {
            common: {
                save: 'Save',
                delete: 'Delete',
                cancel: 'Cancel',
                close: 'Close',
                clear: 'Clear',
                import: 'Import',
                export: 'Export',
                preview: 'Preview',
                home: 'Home',
                help: 'Quick Help',
                gotIt: 'Got it, thanks!',
                confirmClear: 'Are you sure you want to clear the workspace? This cannot be undone.',
                uses: 'Uses'
            },
            toolbar: {
                view: 'View:',
                clearAll: 'Clear All',
                importDsl: 'Import DSL',
                previewDsl: 'Preview DSL',
                renameView: 'Rename View',
                homeTitle: 'Back to System Landscape'
            },
            sidebar: {
                title: 'C4 Elements',
                tipLandscape: 'Tip: Double-click a System to enter its Containers view.',
                tipDrilldown: 'Tip: Drag elements onto the canvas. They will be automatically parented to the current context.',
                notAllowed: 'This element is not allowed in a {{type}} view'
            },
            elements: {
                person: 'Person',
                softwareSystem: 'Software System',
                container: 'Container',
                component: 'Component',
                new: 'New {{type}}',
                external: 'External',
                personDesc: 'Represents one of the human users of your software system (e.g., Customers, Staff, Admin).',
                softwareSystemDesc: 'The highest level of abstraction. Represents a technical solution that adds value to users.',
                containerDesc: 'A separately deployable/runnable unit (e.g., Docker container, Database, Web App, File System).',
                componentDesc: 'A grouping of related functionality behind an interface (e.g., Controller, Repository, Service).'
            },
            properties: {
                title: 'Properties',
                noSelection: 'Select an element to edit properties',
                elementProps: 'Element Properties',
                name: 'Name',
                description: 'Description',
                technology: 'Technology',
                external: 'External System',
                actions: 'Actions',
                createComponentView: 'Create Component View',
                placeholders: {
                    name: 'e.g., Payment Gateway',
                    description: 'e.g., Handles transactions',
                    technology: 'e.g., Java / Spring'
                },
                relationships: 'Relationships',
                addRelationship: 'Add Relationship',
                targetElement: 'Target Element',
                selectTarget: 'Select target...',
                outbound: 'Outbound',
                inbound: 'Inbound',
                direction: 'Direction',
                toElement: 'To Element',
                fromElement: 'From Element',
                outShort: 'OUT',
                inShort: 'IN',
                parent: 'Parent Identifier',
                noRelationships: 'No connections found'
            },
            views: {
                landscape: 'Root',
                landscapeDesc: 'Auto-generated landscape view',
                components: '{{name}} - Components',
                componentsDesc: 'Component view state for {{name}}',
                autoGenerated: 'Auto-generated {{type}} view'
            },
            help: {
                title: 'C4 Model Guide',
                subtitle: 'Learn how to create Structurizr-compatible architecture diagrams',
                tabs: {
                    model: 'C4 Model Elements',
                    hierarchy: 'Nesting Rules',
                    dsl: 'Structurizr Compatibility'
                },
                rules: {
                    subtitle: 'Strict hierarchy is mandatory for Structurizr compatibility:',
                    system: 'Software System can contain Containers.',
                    container: 'Container can contain Components only.',
                    person: 'Person and Software System are typically top-level in a landscape.',
                    smartPaletteTitle: 'Smart Palette Behavior',
                    smartPaletteDesc: 'The sidebar palette automatically disables elements that don\'t belong in your current view.',
                    containerView: 'Only Containers are enabled. Adding a Person here is invalid.',
                    componentView: 'Only Components are enabled. Focus is strictly on the internal logic.',
                    proTip: 'If an element is grayed out, it means you\'re in a drill-down view. Return to Home (Landscape) to add top-level elements.'
                },
                dslInfo: {
                    title: 'Structurizr DSL Compatibility',
                    subtitle: 'To ensure your diagrams work 100% in Structurizr CLI/Cloud:',
                    handle: 'What we handle',
                    avoid: 'Avoid these',
                    handleItems: [
                        'External system tagging (!External)',
                        'Technology & Description fields',
                        'View-specific element positioning'
                    ],
                    avoidItems: [
                        'Creating components outside containers',
                        'Circular parenting (e.g., A in B, B in A)',
                        'Duplicate element names at the same level',
                        'Using illegal characters in names'
                    ]
                }
            },
            modals: {
                import: {
                    title: 'Import Structurizr DSL',
                    subtitle: 'Upload a .dsl file or paste DSL code',
                    uploadLabel: '📁 Upload .dsl file',
                    pasteLabel: '📋 Paste DSL code',
                    or: 'or',
                    importBtn: 'Import from Text',
                    importing: 'Importing...'
                },
                editor: {
                    title: 'Preview Structurizr DSL',
                    subtitle: 'View and edit auto-generated DSL code',
                    copy: 'Copy to Clipboard',
                    download: 'Download .dsl',
                    apply: 'Apply Changes',
                    applied: 'Changes applied to workspace'
                }
            }
        }
    },
    ru: {
        translation: {
            common: {
                save: 'Сохранить',
                delete: 'Удалить',
                cancel: 'Отмена',
                close: 'Закрыть',
                clear: 'Очистить',
                import: 'Импорт',
                export: 'Экспорт',
                preview: 'Предпросмотр',
                home: 'Главная',
                help: 'Справка',
                gotIt: 'Понятно!',
                confirmClear: 'Вы уверены, что хотите очистить рабочую область? Это действие нельзя отменить.',
                uses: 'Использует'
            },
            toolbar: {
                view: 'Вид:',
                clearAll: 'Очистить всё',
                importDsl: 'Импорт DSL',
                previewDsl: 'Просмотр DSL',
                renameView: 'Переименовать вид',
                homeTitle: 'Вернуться к Ландшафту системы'
            },
            sidebar: {
                title: 'Компоненты C4',
                tipLandscape: 'Подсказка: Дважды кликните по Системе, чтобы перейти к её Контейнерам.',
                tipDrilldown: 'Подсказка: Перетащите элементы на канвас. Они будут автоматически привязаны к текущему контексту.',
                notAllowed: 'Этот элемент не разрешен в виде {{type}}'
            },
            elements: {
                person: 'Пользователь',
                softwareSystem: 'Система',
                container: 'Контейнер',
                component: 'Компонент',
                new: 'Новый {{type}}',
                external: 'Внешний',
                personDesc: 'Представляет одного из пользователей вашей программной системы (например, клиенты, персонал, админ).',
                softwareSystemDesc: 'Самый высокий уровень абстракции. Представляет техническое решение, приносящее пользу пользователям.',
                containerDesc: 'Отдельно развертываемый или исполняемый юнит (например, Docker-контейнер, база данных, веб-приложение).',
                componentDesc: 'Группировка связанной функциональности за интерфейсом (например, контроллер, репозиторий, сервис).'
            },
            properties: {
                title: 'Свойства',
                noSelection: 'Выберите элемент для редактирования',
                elementProps: 'Свойства элемента',
                name: 'Название',
                description: 'Описание',
                technology: 'Технология',
                external: 'Внешняя система',
                actions: 'Действия',
                createComponentView: 'Создать вид компонентов',
                placeholders: {
                    name: 'напр., Платежный шлюз',
                    description: 'напр., Обрабатывает транзакции',
                    technology: 'напр., Java / Spring'
                },
                relationships: 'Связи',
                addRelationship: 'Добавить связь',
                targetElement: 'Целевой элемент',
                selectTarget: 'Выберите цель...',
                outbound: 'Исходящая',
                inbound: 'Входящая',
                direction: 'Направление',
                toElement: 'К элементу',
                fromElement: 'От элемента',
                outShort: 'ИСХ',
                inShort: 'ВХОД',
                parent: 'Родительский элемент',
                noRelationships: 'Связей не найдено'
            },
            views: {
                landscape: 'Корень',
                landscapeDesc: 'Автоматически сгенерированный ландшафт',
                components: '{{name}} - Компоненты',
                componentsDesc: 'Состояние вида компонентов для {{name}}',
                autoGenerated: 'Автоматический вид {{type}}'
            },
            help: {
                title: 'Руководство по C4',
                subtitle: 'Узнайте, как создавать диаграммы архитектуры, совместимые со Structurizr',
                tabs: {
                    model: 'Элементы C4',
                    hierarchy: 'Правила вложенности',
                    dsl: 'Совместимость со Structurizr'
                },
                rules: {
                    subtitle: 'Строгая иерархия обязательна для совместимости:',
                    system: 'Система может содержать Контейнеры.',
                    container: 'Контейнер может содержать только Компоненты.',
                    person: 'Пользователь и Система обычно находятся на верхнем уровне ландшафта.',
                    smartPaletteTitle: 'Умная палитра',
                    smartPaletteDesc: 'Палитра автоматически отключает элементы, которые не подходят для текущего вида.',
                    containerView: 'Разрешены только Контейнеры. Добавление Пользователя здесь недопустимо.',
                    componentView: 'Разрешены только Компоненты. Фокус строго на внутренней логике.',
                    proTip: 'Если элемент серый, значит вы в режиме детализации. Вернитесь на Главную (Ландшафт), чтобы добавить элементы верхнего уровня.'
                },
                dslInfo: {
                    title: 'Совместимость Structurizr DSL',
                    subtitle: 'Чтобы ваши диаграммы на 100% работали в CLI/Cloud:',
                    handle: 'Что поддерживаем',
                    avoid: 'Чего избегать',
                    handleItems: [
                        'Теги внешних систем (!External)',
                        'Вложенные узлы развертывания',
                        'Поля технологии и описания',
                        'Позиционирование элементов для конкретных видов'
                    ],
                    avoidItems: [
                        'Создание компонентов вне контейнеров',
                        'Циклическая вложенность (напр., A в B, B в A)',
                        'Дублирование имен на одном уровне',
                        'Использование недопустимых символов в именах'
                    ]
                }
            },
            modals: {
                import: {
                    title: 'Импорт Structurizr DSL',
                    subtitle: 'Загрузите .dsl файл или вставьте код',
                    uploadLabel: '📁 Загрузить .dsl файл',
                    pasteLabel: '📋 Вставить DSL код',
                    or: 'или',
                    importBtn: 'Импортировать текст',
                    importing: 'Импорт...'
                },
                editor: {
                    title: 'Просмотр Structurizr DSL',
                    subtitle: 'Просмотр и редактирование сгенерированного кода',
                    copy: 'Копировать',
                    download: 'Скачать .dsl',
                    apply: 'Применить изменения',
                    applied: 'Изменения применены'
                }
            }
        }
    }
};

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        resources,
        fallbackLng: 'en',
        detection: {
            order: ['cookie', 'localStorage', 'navigator', 'htmlTag'],
            caches: ['cookie', 'localStorage'],
        },
        interpolation: {
            escapeValue: false
        }
    });

export default i18n;
