import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
    en: {
        translation: {
            common: {
                save: 'Save',
                delete: 'Delete',
                cancel: 'Cancel',
                close: 'Close',
                clear: 'Clear',
                import: 'Import',
                export: 'Export',
                preview: 'Preview',
                home: 'Home',
                help: 'Quick Help',
                gotIt: 'Got it, thanks!',
                confirmClear: 'Are you sure you want to clear the workspace? This cannot be undone.',
                uses: 'Uses'
            },
            toolbar: {
                view: 'View:',
                clearAll: 'Clear All',
                importDsl: 'Import DSL',
                previewDsl: 'Preview DSL',
                homeTitle: 'Back to System Landscape'
            },
            sidebar: {
                title: 'C4 Elements',
                tipLandscape: 'Tip: Double-click a System to enter its Containers view.',
                tipDrilldown: 'Tip: Drag elements onto the canvas. They will be automatically parented to the current context.',
                notAllowed: 'This element is not allowed in a {{type}} view'
            },
            elements: {
                person: 'Person',
                softwareSystem: 'Software System',
                container: 'Container',
                component: 'Component',
                new: 'New {{type}}',
                external: 'External'
            },
            properties: {
                title: 'Properties',
                noSelection: 'Select an element to edit properties',
                elementProps: 'Element Properties',
                name: 'Name',
                description: 'Description',
                technology: 'Technology',
                external: 'External System',
                actions: 'Actions',
                createComponentView: 'Create Component View',
                placeholders: {
                    name: 'e.g., Payment Gateway',
                    description: 'e.g., Handles transactions',
                    technology: 'e.g., Java / Spring'
                },
                relationships: 'Relationships',
                addRelationship: 'Add Relationship',
                targetElement: 'Target Element',
                selectTarget: 'Select target...',
                outbound: 'Outbound',
                inbound: 'Inbound',
                outShort: 'OUT',
                inShort: 'IN'
            },
            views: {
                landscape: 'System Landscape',
                landscapeDesc: 'Auto-generated landscape view',
                components: '{{name}} - Components',
                componentsDesc: 'Component view state for {{name}}',
                deployment: '{{name}} - Deployment',
                deploymentDesc: 'Deployment view for {{name}}',
                autoGenerated: 'Auto-generated {{type}} view'
            },
            help: {
                title: 'C4 Model Guide',
                subtitle: 'Learn how to create Structurizr-compatible architecture diagrams',
                tabs: {
                    model: 'C4 Model Elements',
                    hierarchy: 'Nesting Rules',
                    dsl: 'Structurizr Compatibility'
                },
                rules: {
                    title: 'The Golden Rules of Nesting',
                    subtitle: 'Strict hierarchy is mandatory for Structurizr compatibility:',
                    system: 'Software System can contain Containers.',
                    container: 'Container can contain Components only.',
                    person: 'Person and Software System are typically top-level in a landscape.',
                    smartPaletteTitle: 'Smart Palette Behavior',
                    smartPaletteDesc: 'The sidebar palette automatically disables elements that don\'t belong in your current view.',
                    containerView: 'Only Containers are enabled. Adding a Person here is invalid.',
                    componentView: 'Only Components are enabled. Focus is strictly on the internal logic.',
                    proTip: 'If an element is grayed out, it means you\'re in a drill-down view. Return to Home (Landscape) to add top-level elements.'
                },
                dslInfo: {
                    title: 'Structurizr DSL Compatibility',
                    subtitle: 'To ensure your diagrams work 100% in Structurizr CLI/Cloud:',
                    handle: 'What we handle',
                    avoid: 'Avoid these',
                    handleItems: [
                        'External system tagging (!External)',
                        'Nested deployment nodes',
                        'Technology & Description fields',
                        'View-specific element positioning'
                    ],
                    avoidItems: [
                        'Creating components outside containers',
                        'Circular parenting (e.g., A in B, B in A)',
                        'Duplicate element names at the same level',
                        'Using illegal characters in names'
                    ]
                }
            },
            modals: {
                import: {
                    title: 'Import Structurizr DSL',
                    subtitle: 'Upload a .dsl file or paste DSL code',
                    uploadLabel: '📁 Upload .dsl file',
                    pasteLabel: '📋 Paste DSL code',
                    or: 'or',
                    importBtn: 'Import from Text',
                    importing: 'Importing...'
                },
                editor: {
                    title: 'Preview Structurizr DSL',
                    subtitle: 'View and edit auto-generated DSL code',
                    copy: 'Copy to Clipboard',
                    apply: 'Apply Changes',
                    applied: 'Changes applied to workspace'
                }
            }
        }
    }
};

i18n
    .use(initReactI18next)
    .init({
        resources,
        lng: 'en',
        fallbackLng: 'en',
        interpolation: {
            escapeValue: false
        }
    });

export default i18n;
